server:
  port: 8080

spring:

  datasource:

    url: ${DB_URL}

    username: ${DB_USERNAME}

    password: ${DB_PASSWORD}

  jpa:

    hibernate:

      ddl-auto: validate

  data:

    redis:

      host: ${REDIS_HOST}

      port: ${REDIS_PORT}

  ai:

    ollama:

      base-url: ${OLLAMA_URL}

      chat:

        model: llama3.2

jwt:

  secret: ${JWT_SECRET}

  expiration: 86400000