spring:

  application:
    name: ai-marketplace-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/aimarketplace_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics
    endpoint:
      health:
        show-details: when_authorized

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: llama3.2

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: u45ft9cm4r8jt40
            client-secret: iue4ty7g4985yvu849g
            scope:
              - openid
              - email
              - profile

server:
  port: 8080

jwt:
  secret: nyucrt549tcbyo467hh67t3j0985wc4uy5icth635gd5tgn84cwv5ny7c48yt938m0n4ct7938
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework.security: DEBUG